SCENARIOS = {
 'storage-csi-timeout': {'phase':'TARGET_STORAGE','message':'PVC pending, CSI provisioning timeout','hidden_truth':'STORAGE.CSI.PROVISIONING_TIMEOUT','capabilities':{'storage.pvc_state':['PVC_PENDING'],'storage.volume_state':['CSI_PROVISIONING_TIMEOUT'],'storage.backend_state':['BACKEND_UNHEALTHY']}},
 'storage-csi-controller-healthy': {'phase':'TARGET_STORAGE','message':'PVC pending, CSI provisioning timeout, backend and controller healthy','hidden_truth':'STORAGE.CSI.PROVISIONING_TIMEOUT','capabilities':{'storage.pvc_state':['PVC_PENDING'],'storage.volume_state':['CSI_PROVISIONING_TIMEOUT'],'storage.backend_state':['BACKEND_HEALTHY']}},
 'storage-csi-controller-error': {'phase':'TARGET_STORAGE','message':'PVC pending, CSI provisioning timeout, backend healthy, controller provisioning error','hidden_truth':'STORAGE.CSI.PROVISIONING_TIMEOUT','capabilities':{'storage.pvc_state':['PVC_PENDING'],'storage.volume_state':['CSI_PROVISIONING_TIMEOUT'],'storage.backend_state':['BACKEND_HEALTHY']}},
 'storage-csi-conflict': {'phase':'TARGET_STORAGE','message':'PVC pending, CSI provisioning timeout, backend healthy, controller provisioning error','hidden_truth':'STORAGE.CSI.PROVISIONING_TIMEOUT','capabilities':{'storage.pvc_state':['PVC_PENDING'],'storage.volume_state':['CSI_PROVISIONING_TIMEOUT'],'storage.backend_state':['BACKEND_HEALTHY']}},
 'storage-csi-backend-healthy': {'phase':'TARGET_STORAGE','message':'PVC pending, CSI provisioning timeout','hidden_truth':'STORAGE.CSI.PROVISIONING_TIMEOUT','capabilities':{'storage.pvc_state':['PVC_PENDING'],'storage.volume_state':['CSI_PROVISIONING_TIMEOUT'],'storage.backend_state':['BACKEND_HEALTHY']}},
 'network-nad-missing': {'phase':'TARGET_NETWORK','message':'Network attachment failed: NAD not found','hidden_truth':'NETWORK.NAD.MISSING','capabilities':{'network.nad_state':['NAD_MISSING'],'network.network_attachment_state':['NETWORK_ATTACHMENT_FAILED'],'network.network_events':['NAD_NOT_FOUND']}},
 'vmware-cbt-retry': {'phase':'SOURCE_TRANSFER','message':'VMware CBT query failed','hidden_truth':'VMWARE.CBT','capabilities':{'vmware.cbt_state':['CBT_FAILED'],'vmware.task_state':['TRANSFER_FAILED'],'vmware.transfer_errors':['CBT_QUERY_FAILED']}},
 'insufficient-evidence': {'phase':'UNKNOWN','message':'Migration failed without diagnostic detail','hidden_truth':'UNKNOWN','capabilities':{}},
 'capability-error': {'phase':'TARGET_STORAGE','message':'PVC pending, CSI provisioning timeout','hidden_truth':'STORAGE.CSI.PROVISIONING_TIMEOUT','capabilities':{'storage.pvc_state':['PVC_PENDING'],'storage.volume_state':['CSI_PROVISIONING_TIMEOUT']}},
 'unknown': {'phase':'UNKNOWN','message':'Migration failed','hidden_truth':'UNKNOWN','capabilities':{}}
}
